APP_NAME="appRevenda"
APP_ENV=production
APP_KEY=base64:vLWgJ6kH2hEvGmoQuMVxMTqAWfBCDCjH8aeSaDulbxo=
APP_DEBUG=false
APP_URL=https://senadevtech.com.br

APP_LOCALE=pt_BR
APP_FALLBACK_LOCALE=pt_BR

APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=senadevtech
DB_USERNAME=appusuario
DB_PASSWORD=881527@Bd

CACHE_DRIVER=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120

SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=redis

CACHE_STORE=database
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_SCHEME=null
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

BOTCONVERSA_BASE_URL="https://backend.botconversa.com.br/api/v1/webhook"
BOTCONVERSA_API_KEY="5cc639a8-3aed-47d9-ae80-473b8a554b78"
BOTCONVERSA_ORIGIN_TAG_ID=16176586

#Depois de mexer no .env da VPS:
# php artisan config:clear
# php artisan cache:clear
# php artisan config:cache